project:
  type: website

website:
  title: "final-project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data provenance.qmd
        text: Data Provenance
      - href: data cleaning.qmd
        text: Data Cleaning
      - href: about me.qmd
        text: About Me

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



