project:
  type: website


website:
  title: "Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:sources
      - href: model.qmd
        text: Model Training
      - href: about.qmd
        text: About

  sidebar:
    - id: sources
      title: "Exploratory Data Analysis"
      style: "floating"
      background: "#ffffff"
      collapse-level: 0
      contents:
        - sector and industry.qmd
        - headquarters.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true