project:
  type: website


website:
  title: "Market Value of Fortune 500 Companies"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:eda
      - href: model.qmd
        text: Model
      - href: sources.qmd
        text: Sources
      - href: about.qmd
        text: About
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/rajarshi-mandal/market-value-of-fortune-500-companies

  sidebar:
    - id: eda
      title: "Background Graphics"
      style: "docked"
      background: '#0080ff'
      collapse-level: 2
      contents: 
        - sector and industry.qmd
        - headquarters.qmd
        - monetary statistics.qmd
        - newcomers and global 500.qmd
        - ceo and employees.qmd

  page-footer: 
    left: "Copyright 2023, Rajarshi Mandal" 
    right: 
      - icon: github
        href: https://github.com/rajarshi-mandal/market-value-of-fortune-500-companies
    background: '#0080ff'
    
  search: 
    location: navbar
    type: textbox
    
  back-to-top-navigation: true
  page-navigation: true


theme:
  light: flatly
  dark: darkly
  
  
format:
  html:
    theme: '#0080ff'
    css: styles.css
    toc: true