project:
  type: website

website:
  title: "Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sector and industry.qmd
        text: Sector and Industry
      - href: headquarters.qmd
        text: Headquarter Locations
      - href: model.qmd
        text: Model Training
      - href: data provenance.qmd
        text: Data Provenance
      - href: about me.qmd
        text: About Me

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



